murdos/musicbrainz-userscripts

- discogs_importer.user.js
Changes adapted from https://github.com/murdos/musicbrainz-userscripts/issues/28
> removes GreaseMonkey's JQuery, uses pure json instead of JSON-P

- bandcamp_importer.user.js
- add missing curly brackets
- add missing semicolons
- fix up global vs local variables (missing var)
- move importer functions to their own namespace
- beautify code
- remove unneeded commented lines
Code behavior shouldn't have changed but risk of conflicts with third-party scripts is heavily reduced.
> Bandcamp importer: tidy up code

- bandcamp_importer.user.js
Sometimes, Bandcamp album contains more tracks in the download than shown for streaming
In this case, append unknown tracks to the imported release to match the download
and remove the stream for free link (if any) as it doesn't match the whole release
This is a bit hacky since there is only one way i found to know how many tracks has the download:
- the info is from meta property description
- hidden tracks don't appear anywhere else
- no title (but sometimes artist lists them in annotations) and of course no duration
- script assumes hidden tracks are at the end of the release (which is very likely though)
Examples:
https://benfrost.bandcamp.com/album/by-the-throat
https://calicogalaxy.bandcamp.com/album/the-great-388-with-bonus-tracks …
> Bandcamp importer: better handling of hidden tracks

- discogs_importer.user.js
https://github.com/murdos/musicbrainz-userscripts/issues/6
Among releases tested:
http://www.discogs.com/release/7079425
http://www.discogs.com/release/7084165
http://www.discogs.com/release/3979680
> Discogs: import disc titles when possible

- discogs_importer.user.js
https://github.com/murdos/musicbrainz-userscripts/issues/31
Tested on http://www.discogs.com/release/5880212
> Handle sub-tracks and their titles

- discogs_importer.user.js
Tested with: http://www.discogs.com/release/1156598
Suggested by https://github.com/murdos/musicbrainz-userscripts/pull/45#issuecomment-108753443
> Calculate total duration of sub-tracks if needed

- lib/mblinks.js
Mechanism to handle duplicated requests to MusicBrainz webservice: if a link is displayed in many places, only one Ajax request will be made, and it will run all registered handlers that have been merged in an array.
> Mblinks optimization

- discogs_importer.user.js
https://github.com/murdos/musicbrainz-userscripts/issues/64
> discogs: fix incorrect artist credit join phrases

- discogs_importer.user.js
https://github.com/murdos/musicbrainz-userscripts/issues/69
> Remove medium title if there is only one medium

- bandcamp_importer.user.js
https://github.com/murdos/musicbrainz-userscripts/issues/72
> Bandcamp: query MB for label, and try to use mbid for it from cache

- beatport_importer.user.js
Make the script on par with BeatPort Pro script, fix almost all issues.
> Beatport classic fixes

- beatport_pro_importer.user.js
Just match keywords in all available languages.
Not a perfect solution, but i don't think there is one.
https://github.com/murdos/musicbrainz-userscripts/issues/71
> Fix up BeatPort Pro for it to work with other languages

- metalarchives_importer.user.js
I wrote a MB importer for http://www.metal-archives.com/ with your lib.
It just parse HTML code. There is no API on this site.
I send it to you.
Any suggest will be appreciated.
> Metal Archive Importer

- discogs_importer.user.js
Fix https://github.com/murdos/musicbrainz-userscripts/issues/93
> Discogs https fix

- takealot.user.js
Pull request for initial Takealot import into Musicbrainz script,
Multi Disc track list not implemented yet
> Initial Takelot import parser to Musicbrainz

- README.md
- cdbaby_importer.user.js
Limited by what CD Baby provides, but it works for simple releases.
> Simple CD Baby importer

- takealot_importer.user.js
- 1. Added link to high res image
- 2. Added import warning if information is buggy
- 3. Parse additional information from Product Information Tab (Release title and label)
- 4. Changed logic to parse different formats in Description tab
- < br > based formatting
- < div > based formatting
- console log and release_maybe_buggy set if unknown
> takealot_importer: pull various additions

- takealot_importer.user.js
release format array created and known formats added.
tested and happy for it to be merged.
> Takealot: Fixed issue 112 (Format)

- takealot_importer.user.js
Added a link back to the MB release using the MBLinks lib.
ready for merging.
> Takealot: Added MBLinks to the header

- fma_importer.user.js
Checks for "play page" button and adds "stream for free" link.
> FMA importer: add "stream for free" link

- fma_importer.user.js
Started converting album_type to valid MB release types. I am not sure how to find more kinds of FMA album_types...
Test with this release: http://freemusicarchive.org/music/Kyle_Eyre_Clyd/Live_on_WFMUs_Strength_Through_Failure_with_Fabio_Roberti_8132015/
> Use "broadcast" type for "Radio Program" album_type

- dgdecca_importer.user.js
As suggested by @ListMyCDs.com in https://musicbrainz.org/edit/41284376
> DG/Decca importer: small fixes

- mb_discids_detector.user.js
See https://github.com/murdos/musicbrainz-userscripts/issues/139
> mb_discids_detector: Add redacted.ch

- .gitignore
- README.md
- batch-add-recording-relationships.user.js
- expand-collapse-release-groups.user.js
- fast-cancel-edits.user.js
- set-recording-comments.user.js
Merge userscripts from @mwiencek's repository at https://bitbucket.org/mwiencek/userscripts into this one.
Permission asked and given at https://chatlogs.metabrainz.org/brainzbot/musicbrainz/msg/3852183/
> Merge in bitmap’s userscripts

- bandcamp_importer.user.js
- bandcamp_importer_helper.user.js
- batch-add-recording-relationships.user.js
- beatport_classic_importer.user.js
- beatport_importer.user.js
- cd1d_importer.user.js
- cdbaby_importer.user.js
- dgdecca_importer.user.js
- discogs_importer.user.js
- encyclopedisque_importer.user.js
- expand-collapse-release-groups.user.js
- fast-cancel-edits.user.js
- fma_importer.user.js
- juno_download_importer.user.js
- lastfm_importer.user.js
- loot_importer.user.js
- mb_discids_detector.user.js
- mb_relationship_shortcuts.user.js
- mb_ui_enhancements.user.js
- metalarchives_importer.user.js
- qobuz_importer.user.js
- set-recording-comments.user.js
- takealot_importer.user.js
Related to https://github.com/murdos/musicbrainz-userscripts/pull/171
> Change version format on all scripts

- loot_importer.user.js
> granted unsafeWindow

- qobuz_importer.user.js
Change mozilla-specific property to standard.
> qobuz_importer.user.js: fix #203

- bandcamp_importer.user.js
- bandcamp_importer_helper.user.js
- beatport_classic_importer.user.js
- beatport_importer.user.js
- cd1d_importer.user.js
- cdbaby_importer.user.js
- discogs_importer.user.js
- fma_importer.user.js
- juno_download_importer.user.js
- lib/logger.js
- loot_importer.user.js
- metalarchives_importer.user.js
- qobuz_importer.user.js
- takealot_importer.user.js
and grant unsafeWindow for scripts that actually use it.
> Remove unsafeWindow usage in logger and in scripts that don't need it

- lib/mbimport.js
Moved 'home' to arguments as an optional parameter with a default value, to allow it to be changed for scripts that don't live at murdos' github.  
Also fixed a few 'var's that should have been 'let's - 'i' wasn't scoped, so the 2nd, 3rd, and 4th 'var i' statements were attempting to redeclare an already existing 'i'.  Now they're all scoped to just the loop.
> Friendlier make edit note

- discogs_importer.user.js
Handle Barbados, The and lathe cut.
> Fix #214 and #215

- qobuz_importer.user.js
> qobuz_importer.user.js: fix for #217

- discogs_importer.user.js
- digi-pak — wallmart
- digipack — fnac — https://fr.wikipedia.org/wiki/Digipack
- digi-pack
- digi pack — fnac
As spotted by @liftarn in #277.
> Match more than strictly digipak

- edit-instrument-recordings-links.user.js
For some reason the React conversion meant this is now child 1, not child 3.
> Update childNode after React conversion

- bandcamp_importer.user.js
> Fix Bandcamp label name initialization from backlink

- beatport_importer.user.js
It seems one has to be logged in to beatport for this patch to work
It should fix https://github.com/murdos/musicbrainz-userscripts/issues/154
> Reload Playables if empty

- juno_download_importer.user.js
This commit fixes the Juno Download import script which has been broken for some time. No lint errors or warnings.
I've tested the updates on the following releases:
- Single artist release with tracks with multiple artist credits - https://www.junodownload.com/products/alixander-iii-heavy-friends-part-2/2871174-02/
- Release with multiple artist release credits - https://www.junodownload.com/products/lpm-mix-fairbanks-shee-home-turf-ep/4249499-02/
- Single artist release - https://www.junodownload.com/products/hotmood-disco-de-los-muertos/3716815-02/
- VA release - https://www.junodownload.com/products/killekill-megahits-iii/3790832-02/
Note that testing was performed using Violentmonkey running in Brave on Linux only.
> Fix Juno Download userscript

- lib/mbimport.js
Uses [const](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const), [arrow functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions), [reduce](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce) and [object destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Object_destructuring) features, which are supported by modern browsers
> replaces for with reduce for counting tracks

- bandcamp_importer.user.js
Minor change to set the release barcode if a UPC is present.
> bandcamp_importer: seed barcode if present

- README.md
- boomkat_importer.user.js
This is a first attempt at a Boomkat importer. The code isn't pretty but it does seem to pass the linter clean. It correctly detects the selected format (e.g. Digital, CD, LP, etc.) and sets the link types and media accordingly.
Reviews welcome :)
> Add Boomkat importer.

- README.md
- naxos_library3_importer.user.js
- naxos_library_importer.user.js
Importers for naxosmusiclibrary.com (old version of the website, still available) and nml3.naxosmusiclibrary.com (new version)
> Add naxos importer scripts

- lib/mbimport.js
As mentioned in https://github.com/murdos/musicbrainz-userscripts/pull/326#issuecomment-730528478
> Add missing parameters in mbimport documentation

- vgmdb_importer.user.js
Turns out `getDay()` returns weekday. Whoops! And also we should use UTC dates.
Fixes #361. Fixes #375.
> vgmdb_importer: Fix bugs and other problems

- discogs_importer.user.js
Discogs has rolled out a new layout for release pages on 2021-08-09: [Announcement](https://www.discogs.com/forum/thread/828514?page=3#8916061)
This breaks the injection of the import button and MB links on release pages, other pages (artist, label, master) are not affected so far.
With this commit, the following changes are made to fix #411 and #354:
- Update selectors for the sections which should be enhanced with MB links
- Separate working and broken selectors but keep all of them for now
- Find a new selector to inject the import button into the sidebar (not sure why there were three alternative selectors previously)
- Duplicate some of Discogs' CSS to fix the layout because they seem to use dynamically generated class names now
> Discogs importer: Adapt to new release page layout

- bandcamp_importer.user.js
The consensus seems to be that this is the maintained instance now.
> bandcamp_importer: Update atisket URL.

- lib/mbimport.js
- Fix doc `artist_credit.mbid` (not `artist_mbid`)
- Allow no labels or no urls without crashing the script
> Small mbimport.js fixes

- juno_download_importer.user.js
The HTML changed a few weeks (months?) ago, breaking the importer. Make it work again.
> Fix Juno Download importer.

- bandcamp_importer.user.js
Scratches a personal itch of mine.
I should probably note that I am not a JavaScript developer. If there's a better way of doing this, I'd be happy to hear about it.
Fixes #322
> bandcamp_importer: handle IA'd pages

- set-recording-comments.user.js
Fill the injected recording comment inputs based on the MBID of the associated recordings instead of the index. This was based on the assumption that the position of the input equals the absolute track position which is not the case if only [medium 4 of a release](https://musicbrainz.org/release/9c3f38c7-342b-4a2d-a160-6314abef8cf9/disc/4) is expanded (for example).
With the old approach the script always loads the disambiguation comments for the first tracks on the release, independent of the currently expanded medium. This lead to wrong initial comments for `/disc` URLs ("supported" since #457), see [report on the forum](https://community.metabrainz.org/t/script-set-recording-comments-user-js/541943/15?u=kellnerd).
Edit submission is already based on MBIDs, so there is no problem with …
> recording-comments: Fill input based on recording MBID instead of index

- mb_discids_detector.user.js
OPS has changed its HTML a little bit, resulting in broken artist/album detection.
> mb_discids_detector: Fix artist/album detection on OPS.

- mb_ui_enhancements.user.js
This should fix issue https://github.com/murdos/musicbrainz-userscripts/issues/506 .
> Fix for ISRC year highlighting.

- mb_ui_enhancements.user.js
Updated mb_ui_enhancements userscripts to create URL of working a-tisket server
> Using working website for a-tisket

- mb_ui_enhancements.user.js
Just a few small improvements to the userscript, mostly to prevent some issues I ran into when using it on my machine. I'd be happy to discuss the changes further, if you'd like. 🙂
> Improvements to the Musicbrainz UI enhancements userscript

- batch-add-recording-relationships.user.js
Load **language list** from `/release/add` page, as it is no longer available from `/work/create` page.
This would fix #175.
> Restore work language list

- batch-add-recording-relationships.user.js
Also appends a userscript signature to the Edit Note.
Also cleanup metadata block.
This would fix #189.
> Add Make Votable checkbox and Edit Note text area

- beatport_importer.user.js
Fixed a problem where the script was not working due to changes in the query key.
> beatport_importer: adapt to query key change

- set-recording-comments.user.js
Fixes #563.
Also change deprecated `@include` to `@match`.
> set-recording-comments.user.js: Fix @match

- mb_relationship_shortcuts.user.js
> mb_relationship_shortcuts: add beatport as a possible release relationship

- bandcamp_importer.user.js
- Added a link to seed the UPC into the Harmony importer
- Moved the seed links (Atisket + Harmony) onto their own row
>  bandcamp_importer: add Harmony seed/import link

- README.md
- boomkat_importer.user.js
Rather than fight with jQuery conflicts, just use regular JS.
> boomkat_importer: Fix for recent Boomkat changes.

- deezer_importer.user.js
- lib/mbimportstyle.js
> fix(deezer): `Import into MB` button style is off on Deezer

- qobuz_importer.user.js
> Qobuz fixes: call API directly; adjust for renamed elements

- beatport_importer.user.js
- boomkat_importer.user.js
- deezer_importer.user.js
- I will be doing it step by step, first 3 are ready and tested.
> chore: convert @include to @match directive in all userscripts, part 1

- qobuz_importer.user.js
- also fix button styles, as right now their positioning is quite off;
- didn't really touch Classical music logic, since I never work with it and don't know the importing rules;
- release pages seem to support locale-independent URLs, but artist pages and label pages do not: Qobuz returns 404 if locale or any other parts of the slug are removed. So we will have to keep it as is and look up accordingly.
For reference:
1. Release URL: https://www.qobuz.com/us-en/album/fujiwarp-01-hiromichi-fujiwara/vulp1p7pxc6vc
2. Artist URL: https://www.qobuz.com/us-en/interpreter/hiromichi-fujiwara/22742844
3. Label URL: https://www.qobuz.com/us-en/interpreter/hiromichi-fujiwara/22742844
> feat(qobuz_importer): add Release page linking with MB
