murdos/musicbrainz-userscripts

- cd1d_importer.user.js
CD1D.com is a french website distributing independent music, in digital and physical formats.
The importer supports following features:
- release date, including "today", and "yesterday"
- label
- multiple artists
- vinyl/CD/digital (whenever possible, not perfect due to the way releases are listed)
- track times conversion (the website don't use mm:ss format)
- add a download link for digital, a mailorder link for physical
> CD1D importer

- bandcamp_importer.user.js
- lib/mblinks.js
Based on the discogs importer code, but with few improvements:
- localStorage entries can expire (set to 1 week)
- code has its own namespace, and is more generic (it will move to a lib later)
- prevent jquery libs conflicts (GM vs website), jquery upgraded to 2.1.4
Test: https://redfang.bandcamp.com/album/whales-and-leeches-deluxe-version
> Bandcamp importer: add links to matching MB artist and releases

- beatport_pro_importer.user.js
- lib/import_functions.js
Fixed:
- invisible import button
- more tracks than in the release
- release artist credit were the ones of the last track
- remove 'Original Mix' from track titles
- update jquery to recent version
- prevent jquery conflicts
- use relative paths for lib
> BeatPort Pro: make it work again

- bandcamp_importer.user.js
Currently, one has to add the domain to userscript preferences for pages provided by bandcamp
but under another domain (ie. http://bearthemammoth.com/album/yamadori)
This change makes the `@include` wider (it may match totally unrelated pages) and test for
a bandcamp-specific object before doing anything.
Please review and test, i'm still not sure if it is a good idea, but it simplifies things since nowaday a lot of artists/labels are using bandcamp engine with their own domains.
Another approach would be to make 2 userscripts with different include rules, sharing the same code.
> bandcamp_importer: support bandcamp pages having their own domain

- lastfm_importer.user.js
- it doesn't import much data, since last.fm has almost none but the tracklist (a bit more if last.fm uses MB data, but in this case no point in importing...)
- it is very unclear which release last.fm is listing, editor have to take care of formats, release dates, label, etc...
- artist credits are somehow random, don't expect miracles
I don't think last.fm is a good source for releases, it should only be used in last resort.
Suggested by https://github.com/murdos/musicbrainz-userscripts/issues/57
> Add last.fm importer

- discogs_importer.user.js
- lib/import_functions.js
- lib/mbimportstyle.js
While an entity is not found, display a small link which allows one to query MB for this entity.
For the case the discogs element may match more than one MB entities (ie. label or place), one search link for each is displayed (at the moment only in release > companies).
> Discogs importer: display links for direct search of entities on MB

- bandcamp_importer.user.js
- there is no indicator of compilation or split release, etc..
- bandcamp builds titles from artist + track title, "artist - title"
- only works if ALL tracks have this format
- set release artist to Various Artists only when original release artist contains Various or Various artists AND we detect all tracks in format "artist - title"
I did tests, and didn't find any problematic releases yet (but i guess they'll be some)
Examples:
http://tartarusrecords.com/album/split-2
http://shop.bornbadrecords.net/album/wizzz-french-psychorama-vol-3
https://bedroomcassettemasters.bandcamp.com/album/bedroom-cassette-masters-1980-89-volume-one
> Bandcamp: try to detect multiple artists releases

- discogs_importer.user.js
Fix Discogs import does not properly understand "Single Sided"
https://github.com/murdos/musicbrainz-userscripts/issues/66
> Discogs: "Single Sided" != "Single"

- discogs_importer.user.js
http://www.discogs.com/release/1520366 has a track with buggy position,
the script is placing the track at the wrong position because of this.
2-.23 	Le Carnaval 	0:26
2-.23 is now parsed as it was 2-23
This patch shouldn't affect non-buggy track positions.
> Issue 89: ignore repeated '.' or '-' in (buggy) track position

- discogs_importer.user.js
Musicbrainz normalizes urls to http, so we can't search for https urls.
> Use http url for querying musicbrainz

- discogs_importer.user.js
This change shuffles the MBz box priorities up so that the 'Import into' and 'Search in MBz' buttons show up immediately under the Release information when present, above the Marketplace boxes.
On smaller windows, this box requires scrolling down to find, and is doubly obnoxious when having to come back to reference information and scroll back up.
Additionally, it also bumps the download and update URLs to use the raw.githubusercontent.com domain.
Tested by myself on Chrome 48.0.2564.103 (64-bit), using Tampermonkey 3.12.58, on OS X 10.11.2. Also mentioned in #musicbrainz awaiting further feedback.
> Move the MBz import box up between the Discogs Collection and Marketplace boxes

- fma_importer.user.js
This is the initial script for testing and comments please;
It uses the FMA API (http://freemusicarchive.org/api/docs/) rather than page information to build the release object.
Script work as follows:
- Check if API key is set for registered user
- The first time you enter your API KEY it will store it with localStorage.
- Parse data that is only obtainable from the website (including the album id needed for API & release label)
- Do all the AJAX calls to retrieve the data from API (The FMA API limit results to 20 per call)
- Once all the data retrieved a release object is build and presented.
- UI: added some on-page indicators to track API call status during debug.
Debug set to true during testing phase
> FMA: initial import seeder

- dgdecca_importer.user.js
New importer from Deutsche Grammophon/Decca website
Adapted from https://greasyfork.org/en/scripts/24375-import-dg-decca-releases-to-musicbrainz in order to use the same downloadURL/icon scheme as others in murdos/musicbrainz-userscripts
The userscript probably needs more comments, but at least it has been working well for me
> dgdecca_importer

- discogs_importer.user.js
Musicbrainz no longer normalizes discogs URLs to http, so we now need to search for the https form.
Fixes #124
> Use https urls when querying musicbrainz

- mb_relationship_shortcuts.user.js
If a release group or label URL included additional GET parameters, namely ?page=X when switching to another page, the script regex would not pick it up anymore.
> Fix #136: mb_relationship_shortcuts.user.js not handling GET parameterrs properly

- README.md
- beatport_classic_importer.user.js
- beatport_importer.user.js
- beatport_pro_importer.user.js
Changed all references to Beatport to use the current names of the services. Fixed the broken Beatport (Pro) script by using the `ProductDetail` object instead of a bunch of parsings that didn't work. Also fixed an unused variable, a left-over comma and non-strict comparisons.
`ProductDetail` could probably be used for more, I only fixed what was broken.
Makes #130 obsolete. Fixes #125. Doesn't fix(!) #62 which is still an issue for me.
Minor note: Beatport keeps (under `date`) both `published` and `released` values. I figure that they could possibly be meant to be used for the date published on Beatport and worldwide release date respectively, so I used `published`. I haven't found any documentation or releases where the values are different from each other, even though some were …
> Update Beatport scripts

- mb_relationship_shortcuts.user.js
- updated the script so that a few "other databases" relationships are shown aswell; might be kludgy but better than not showing them at all
- changed most of the favicons to use the copies stored on the MusicBrainz server
- remove unused logger, updated to latest jQuery without any noticeable breakage
- fixed some minor code warnings
> Display more relationships + minor changes

- batch-add-recording-relationships.user.js
The MusicBrainz server upgraded from lodash 3.10 to lodash 4.17 (https://github.com/metabrainz/musicbrainz-server/pull/573) on 2017-12-21
Fix by replacing deprecated syntax
> Adapt batch-add-recording-relationships.user.js script to lodash 4 (closes #163)

- set-recording-comments.user.js
Script does no longer fetch recording comments for edit.
It’s ending up in submitting recording comment removal edits!
Because of `_.pluck is not a function` issue.
---
I have also cleaned up <del>`@include`</del>, `@exclude` and `@match`.
> URGENT: Recording comment removal edits are queued!

- mb_relationship_shortcuts.user.js
Issue: `mb_relationship_shortcuts.user.js` triggers the following exception under certain circumstances:
````
TypeError
relationsIconsURLs[targettype] is undefined
````
This patch tests if the `targettype` is appropriate for relationships shortcut display.
> Check target type in shorcut for relationships

- fast-cancel-edits.user.js
I’m just fixing the version number that went down instead of moving up with a82234ebf031203e25f8246e4634277acb0cdc9c, that was made in <ins>2016</ins>-06-07, not in <del>2015</del>-06-07 — [spotted by psychoadept](https://community.metabrainz.org/t/your-favourite-user-scripts-for-musicbrainz-so-that-they-can-be-used-while-redesigning/354379/30?u=jesus2099).
> Fixing my old date mistake that makes old users stay on the old version

- mb_relationship_shortcuts.user.js
- tools/update_version.py
As reported by @jesus2099 in https://github.com/murdos/musicbrainz-userscripts/commit/b365af8cde4117cd65bb2f8274b5c0bb7e83d9a8#commitcomment-27623531 and https://github.com/murdos/musicbrainz-userscripts/commit/b365af8cde4117cd65bb2f8274b5c0bb7e83d9a8#commitcomment-27605542, version part numbers starting with `0` are not supported by Chrome at least.
This patch fixes the tool to update version so as to stop padding month and day with leading `0` and to start the fourth number/part of version from `1` instead of `0`.
As ane example, it also bumps version number for recently updated `mb_relationship_shortcuts.user.js` which caused this bug to be reported.
If this patch does not generate other any auto update bug for other platform/browser, it should be fine to bump the version number of …
> Fix update version to make sub-version numbers without leading 0

- discogs_importer.user.js
Acute accents are wrong and they also make the MB track parser add spaces around it.
Example https://www.discogs.com/release/7809058 → https://musicbrainz.org/edit/51145485
This is only small change proposal on track titles but if wanted,
it should be done for track artists and release title and artists as well.
Maybe as a new cleanup function.
Tell me.
> Discog importer: Turn all acute accents used as apostrophe into the proper character

- bandcamp_importer.user.js
- Bandcamp now redirects all http URLs to https
- They didn't change URLs in DOM data yet, most are still http
- MB changed Bandcamp URLs normalization to use https
- MB didn't change old Bandcamp http URLs in the database yet
Basically this breaks some features of the importer, like detection of existing artists, labels, and releases (small icons)
Since the importer has no way to know if the url is stored as http or https, the result is quite random.
One solution would be to query for both, doubling the number of requests to the web service.
Another, much better, is to convert all old Bandcamp http URLs in MB database to https (all new URLs are normalized to https).
This patch only fix http URLs still appearing in pages, and look up for https URLS on the web service.
So, at the moment, …
> Bandcamp Importer: Use only https URLs

- lib/mbimport.js
I used "Digital download" as a release.comment on recent qobuz_importer.user.js updates. This will add support for passing the comment to MusicBrainz release editor seeding.
> mbimport.js: Add support for disambiguation comment

- deezer_importer.user.js
New userscript for importing Deezer releases into Musicbrainz. 
Here's a few releases that were imported using the script:
https://musicbrainz.org/release/0882fb8b-22fa-4d76-9635-ad0cbaa3e3d0
https://musicbrainz.org/release/4bf37487-9684-41de-b0d4-f1653151d53b
https://musicbrainz.org/release/ca9c6b50-85ff-4653-beb6-ba7ec9d23dc7
I don't write JS frequently so please let me know if anything can be improved. The script has been run through eslint and no errors were reported.
> Add Deezer import userscript

- README.md
- edit-instrument-recordings-links.user.js
Tiny userscript that was requested for instrument cleanup and might help people who want to quickly edit recordings to set a better instrument (e.g. after a new instrument is added that previously was only entered as an instrument credit).
>  MusicBrainz: Add recording edit links to instrument pages 

- set-recording-comments.user.js
This is very needed when I want to keep my edits open at the same time of concurrent merges, for instance.
If merge edits are voted down or cancelled, recording comment edits can be cancelled accordingly or voted down at the same time.
- https://musicbrainz.org/edit/61162453#note-61162453-2
- https://musicbrainz.org/search/edits?auto_edit_filter=&order=desc&negation=0&combinator=and&conditions.0.field=release&conditions.0.operator=%3D&conditions.0.name=Popmart%3A+Live+from+Mexico+City&conditions.0.args.0=813469&conditions.2.field=type&conditions.2.operator=%3D&conditions.2.args=204%2C72%2C245&conditions.2.args=74&conditions.3.field=editor&conditions.3.operator=%3D&conditions.3.name=jesus2099&conditions.3.args.0=285909
> New checkbox to “Make all edits votable.” like in all MBS edit pages

- mb_1200px_caa.user.js
This script makes the release/*/cover-art pages use the 1200px “thumbnail” images for the pop‐up/preview instead of the original image, which can speed up loading times significantly for large scans, but should still be high enough definition for most text to be legible.
Additionally it adds a “1200px” link to the “All sizes” lists. This will likely be unneeded as soon as [CAA-88](https://tickets.metabrainz.org/browse/CAA-88) is resolved, but until then it is really nifty to have handy.
Note: A few (older) images may not be available in 1200px.
---
Adding as a PR in case anyone objects to it going into this repository. :) (I’m using it myself right now, and it’s working wonderfully!)
> New userscript: MusicBrainz: 1200px CAA

- bandcamp_importer.user.js
It's often useful to look up the UPC to make sure it's actually a digital release. Make that process easier.
> bandcamp_importer: Make UPC a link to Atisket.

- mb_relationship_shortcuts.user.js
This adapts the width of all subheader rows in the release table on release group pages. Usually there is a single `th`-Element with a `colspan` of 7, which now has to span the additional *Relationships* column that is inserted by this script.
In case the server code changes, only the `colspan` of the first `th` cell is incremented.
**Before:**
**After:**
> mb_relationship_shortcuts: Fix width of subheaders

- lib/mbimport.js
Adding the Parameter "mediums.x.track.y.recording" defined in https://musicbrainz.org/doc/Development/Release_Editor_Seeding
Not sure if this should be documented since it's an optional parameter. I just needed it for https://github.com/loujine/musicbrainz-scripts/blob/master/mb-edit-create_release_from_recording.user.js where I knew the preexisting recording MBID
> Add 'recording' mbid param to release seeder

- expand-collapse-release-groups.user.js
Prevents the injection of a second expand/collapse-button for releases with cover art.
This was caused by the [introduction of a new icon that indicates existing cover art](
https://tickets.metabrainz.org/browse/MBS-4644) and links to the release's cover art page.
https://github.com/metabrainz/musicbrainz-server/pull/1176
> expand-collapse-release-groups: Avoid injecting a second button for a release's cover art link

- batch-add-recording-relationships.user.js
- set-recording-comments.user.js
Lodash has been dropped from MBS and this breaks some userscripts that rely on it.
I've replaced all occurences of `_` (Lodash) with the equivalent methods of `Array` and `Object`.
Fixes #299
> Replace Lodash by built-in ES6 methods

- bandcamp_importer.user.js
Most UPCs on Bandcamp apply to physical releases and there appears to be no way to determine whether a UPC also applies to the digital version. This PR updates the logic to set the barcode when digital download is the only available release.
Example where UPC refers to physical release:
https://gatedrecordings.bandcamp.com/album/in-the-key-of-g
Example where UPC refers to digital release:
https://isophene.bandcamp.com/album/echo-point
> Bandcamp: set barcode if digital only

- README.md
- vgmdb_importer.user.js
Adds an import script using the VGMdb.info API. Works for the most part, but could of course be further refined. Fixes #81.
> Add VGMdb import script

- lib/mbimport.js
I intend to use the annotation field in a future importer script to store release metadata from the importing website (idagio). Add support for it
> Add support for release annotation field in mbimport

- mb_ui_enhancements.user.js
MusicBrainz has a 'native' "Edit Relationships" tab on releases since October 2019: https://tickets.metabrainz.org/browse/MBS-5479 (<https://github.com/metabrainz/musicbrainz-server/commit/5fe0b992921cd5db3da5b359bdd55c1b62ab6cc2>)
> mb_ui_enhancements: Remove "Edit relationships" tab

- mb_1200px_caa.user.js
This link has been added to MusicBrainz itself:
https://tickets.metabrainz.org/browse/MBS-9631
https://github.com/metabrainz/musicbrainz-server/pull/2054
https://github.com/metabrainz/musicbrainz-server/commit/d2a8d04eefddec6a5cfff38b4598e87328a4c7c8
(Not yet live on prod., so not merging this yet.)
> mb_1200px_caa: Remove "1200px" thumbnail link

- set-recording-comments.user.js
The script will now run after the page and all resources are loaded and page scripts have run. This will be later than before and (hopefully) after any React redraws which undid the DOM changes done by the script.
Tested and working with Violentmonkey under Firefox, for Tampermonkey document-idle is the default value anyway.
See https://community.metabrainz.org/t/541943 where the problem has also been reported and where I will ask for some additional test users with different browser / userscript manager setups.
> Make the 'Edit recording comments' button appear again

- set-recording-comments.user.js
Script causes a type error on this page which is unintentionally matched.
> Set recording comments: Exclude "Add release" page

- lib/mbimportstyle.js
Apparently it was an issue only noticeable in deezer.com:
Before the style
After the style
> CSS for the line break in the "Import into MB" button in deezer.com

- hdtracks_importer.user.js
GM has no direct access to the properties of the real `window`, call the `addEventListener` method instead (which is also a cleaner solution).
The script is now also running under GM 4.11 (and still works with Violentmonkey).
> hdtracks: Make the userscript run under Greasemonkey

- vgmdb_importer.user.js
Broke when there was `websites` but no `websites['Commercial']`. Fixes #404.
> vgmdb_importer: Fix websites bug

- expand-collapse-release-groups.user.js
This gives injected tracklists more horizontal space instead of stuffing them into a sub-column of a column. The additional margin is not necessary for injected releases, only for release groups.
Reverting an undocumented change from 02f93f7 which (unintentionally?) abandoned the dedicated `track_tr` row (highlighted in the screenshots below).
I have also fixed the remaining ESLint warnings and did some minor refactorings (replacing index loops with for-of loops where possible, removing an unused parameter) while I was already at it.
> expand-rg: Stretch tracklist tables to the full column width

- mb_relationship_shortcuts.user.js
- Give the icons a bit of margin in all directions, this looks better if there are many icons which float into the next line.
- Remove the fixed column width, this looks ugly for smaller viewports. Often there are not even enough icons to justify such a wide column.
- Exclude artists' recording overview pages:
An MBS update brought a new column which shows the release groups each recording is part of. While it's interesting to see these, the shortcut icons for the RGs are not very appropriate as the page is about recordings.
> Relationship shortcuts: Style tweaks & Exclude artists' recording overview pages

- expand-collapse-release-groups.user.js
- Add a direct link to 'add cover art' to expanded releases:
I have been using this patch for almost two years now, it's great to fill the artwork gaps in a list of releases.
- Open editing-related links in new tabs:
Since these are less likely to be used to speed up browsing (from an artist page down to e.g. a specific recording on a release, skipping the RG and release page) but for batch editing, it makes sense to open these in new tabs by default.
> Expand RGs: Direct link for 'add cover art' & Open new tab for editing links

- set-recording-comments.user.js
A very rough fix, `document-idle` dda9dcb6c14b7ac5ccafd2e1572180b7a281fd19 was eventually not enough for me, 9 times of 10, React still removes the button!
~~It does not fix #399, except if you quickly Expand all mediums, before the second elapses. ;)~~
<ins>I have added [ulugabi work-around](https://community.metabrainz.org/t/script-set-recording-comments-user-js/541943/10?u=jesus2099) for #399: Enable `/disc/123` (medium) URL.</ins>
For #399, it needs to delay the loading to the last moment, when the user clicks the button.
But I have no time for this, at the moment.
> Set recording comments: Delay script and enable medium URL #399 work-around

- deezer_importer.user.js
Sometimes the release information is processed faster than the page is rendered, and the buttons have nothing to attach to. Quick ~~hack~~ fix to wait for the toolbar to appear before rendering the button.
disclaimer: I don't actually know js so I don't know the best way to actually do this. Suggestions are welcome
> deezer: wait for toolbar to appear

- lib/mbimport.js
- lib/mblinks.js
Noticed the MB logo doesn't look so nice, e.g. on https://heilung.bandcamp.com/album/drif:
I've tried hard to find the logo somewhere hosted on https://musicbrainz.org/, but haven't succeeded.
@zas, maybe you know? :)
So for now the new URL is not as nice:
https://raw.githubusercontent.com/metabrainz/design-system/master/brand/logos/MusicBrainz/SVG/MusicBrainz_logo_icon.svg
But as you probably guess from the URL, it's from the official design system here: https://github.com/metabrainz/design-system/blob/master/brand/logos/MusicBrainz/SVG/MusicBrainz_logo_icon.svg
And now it looks nice:
Additionally did a bit of stuff around.
In case you are wondering why I removed the protocol-relative URLs:
https://www.paulirish.com/2010/the-protocol-relative-url/
> Now that SSL is [encouraged for …
> SVG MB logo, more HTTPS + small changes

- mb_discids_detector.user.js
They changed their HTML so here we are again.
Longer term it would make more sense to use the JSON links they provide. I may find some time soonish to actually implement that.
> mb_discids_detector: Fix artist/album detection on OPS again.

- beatport_importer.user.js
This PR adds registration feature of UPC and ISRC on beatport_importer.user.js by using the Beatport API and [kepstin's MagicISRC](https://magicisrc.kepstin.ca/).
> beatport_importer: Add UPC and ISRC support

- beatport_importer.user.js
Beatport website has been updated recently, and the userscript no longer work at all. This PR adapts to these changes, but several problems still remain.
* The new API does not provide track numbers, so there are concerns about whether imported tracks are in the correct order.
* The API is called every 100 tracks, so for a release with more than 100 tracks like [this](https://www.beatport.com/release/a-state-of-trance-1000-celebration-mix-mixed-by-armin-van-buuren-extended-versions/3277362), import will not work properly.
> beatport_importer: Adapt to website changes

- beatport_importer.user.js
Use `length_ms` property instead of `length`.
> beatport_importer: support track length submission in milliseconds

- discogs_importer.user.js
This PR should cover all entity links on artist, label, master and release pages. I replaced all the existing calls to `add_mblinks` as there was a lot of cruft and it was easier to start afresh. I've grouped the calls by page to make it easier to maintain in future. If I've missed anything please let me know.
Calls to `setTimeout` are for elements which are loaded dynamically after the initial page rendering. Timeouts have been chosen arbitrarily - setting them any lower caused random failures on my machine.
Calls to `setInterval` are for elements that are rendered dynamically based on user input (e.g. clicking the "N versions" button on master releases). This approach is not ideal but I don't see another way without making major changes. Again, intervals were set arbitraily and could …
> Discogs: fix missing links on various pages

- discogs_importer.user.js
Label pages are now dynamically loaded in the same way as the artist pages, so the release listing selector has been moved into the function called by setInterval.
> Discogs: Update various element selectors

- beatport_importer.user.js
This change adds a new barcode row to the release info section. If a barcode is set then it is linked to a-tisket:
If the barcode is null then "[none]" is displayed:
> Beatport: Display barcode under catalog number

- discogs_importer.user.js
This PR fixes a typo in a selector and adds a new selector for artists on VA master release pages.
> Discogs: minor updates

- bandcamp_importer.user.js
- lib/mblinks.js
- just stumbled upon the Jira thread that release relationship lookup supports batching now;
- implemented a new function to batch process multiple URLs for MusicBrainz links;
- adjusted the existing logic to utilize the new batch processing feature for discography pages on Bandcamp.
> feat(bandcamp_importer): Bandcamp importer should use batching when searching for MusicBrainz releases

- lib/mbimport.js
- lib/mbimportstyle.js
- it turns out that there's a parent container `#mb_buttons` and that it also needs to be a flex for correctly centering the buttons;
- also makes sure we correctly centre the text inside of the buttons.
Fixes this issue that I introduced:
> fix: global MB buttons style issues after converting them to flexbox

- bandcamp_importer.user.js
- deezer_importer.user.js
- and the quest continues, turns out in order for the shared code to update in an existing extesion, a new version has to be released, of which I had no idea;
- essentially, just bumping the versions of Bandcamp Importer and Deezer Importer here to make sure the fix from #634 is delivered to the users.
> chore(bandcamp_importer,deezer): release new version to fix the import buttons

- discogs_importer.user.js
Add CSS to prevent track credits from overlapping with subsequent track titles when there are many credits per track. Sets height to auto for expanded track credit elements to override Discogs' dynamic height calculation.
<details><summary>After the change (screenshot)</summary>
</details> 
closes #660
> fix(discogs_importer): tracklist text overlap when long credits are present

- bandcamp_importer.user.js
On Bandcamp, labels can appear in at least two forms:
1. **Hosting labels** – own the releases and host them directly under the label's Bandcamp page.
2. **Collection labels** – link to releases hosted on the artist’s own Bandcamp page.
For hosting labels, discography URLs are relative and already handled correctly.  
For collection labels, discography URLs are absolute and currently fail to link correctly because:
- Some URLs include search parameters that must be stripped.
- Our hostname substitution is wrong, since the absolute URL’s hostname differs from the current page’s hostname.
**Fix:**  
- For absolute URLs, strip any search params.  
- Validate the pathname against the existing regex.  
- Rebuild the link using the original hostname from the absolute URL.
Closes #670
> fix(bandcamp_importer): releases on collection-labels discography pages are failed to be linked

- bandcamp_importer.user.js
- lib/mblinks.js
- also fixes a crash on those pages when unsafeWindow.TralbumData is  an empty object;
- if the page hasn't been linked yet, offer a discogs-style lookup;
closes #676
> feat(bandcamp_importer): enhance MB link integration for stub band and label discography pages

- qobuz_importer.user.js
Copied from #703 
It seems Qobuz has changed their UI a little yesterday, they no longer use the `.album-meta__artist` classname and write the artist below the title. Instead, now the artist is following the title, separated by the `by` conjunction, and the HTML/CSS structure is a bit different, so we need to update the script.
After the change:
Closes #703
> fix(qobuz_importer): linked artist is not visible in Qobuz due to changed HTML

- README.md
- beatport_classic_importer.user.js
I tried to discontinue it gracefully, making sure everyone who installed the script will get a notification that it can be deleted. I think we can have it like this for a month/two, and then delete the script entirely.
I've never had to discontinue a user script before, so if there's a better approach, please let me know :)
After this update the script will display a console warning on every website, like so:
Closes #696
> feat(beatport_classic_importer): discontinue Beatport Classic importer script since the old service is gone
